[tool.poetry]
name = "tidal_algorithmic_mixes"
version = "0.1.5"
description = "Common transformers used by the Tidal personalization team."
authors = [
    "Loay <loay@squareup.com>",
    "Tao <tma@squareup.com>",
    "Thomas <talmenningen@squareup.com>"
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/tidal-music/tidal-algorithmic-mixes"

[tool.poetry.dependencies]
python = ">=3.10.13"
pyspark = ">=3.5.0,<=3.6.0"
numpy = ">=1.16.4"
s3fs = ">=2022.11.0"
boto3 = ">=1.24.59"
pandas = ">=1.4.2"
great-expectations = "0.16.15"
scikit-learn = "1.4.0"
alphabet-detector = "0.0.7"
pyarrow = "8.0.0"
tidal-per-transformers = "0.3.1"
torch = "2.2.1"
mlflow = "2.9.2"

[tool.poetry.group.dev.dependencies]
pytest = "8.0.2"
coverage = ">=4.5.2"
pytest-cov = ">=4.1.0"
coveralls = ">=1.6.0"
mock = ">=2.0.0"
moto = ">=3.1.11"
setuptools  = ">=69.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
